package hibernate.pojo;
// Generated Apr 17, 2015 9:43:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblCard generated by hbm2java
 */
public class TblCard  implements java.io.Serializable {


     private String CCardId;
     private TblPlant tblPlant;
     private Set tblVehicleFlights = new HashSet(0);
     private Set tblMappings = new HashSet(0);

    public TblCard() {
    }

	
    public TblCard(String CCardId, TblPlant tblPlant) {
        this.CCardId = CCardId;
        this.tblPlant = tblPlant;
    }
    public TblCard(String CCardId, TblPlant tblPlant, Set tblVehicleFlights, Set tblMappings) {
       this.CCardId = CCardId;
       this.tblPlant = tblPlant;
       this.tblVehicleFlights = tblVehicleFlights;
       this.tblMappings = tblMappings;
    }
   
    public String getCCardId() {
        return this.CCardId;
    }
    
    public void setCCardId(String CCardId) {
        this.CCardId = CCardId;
    }
    public TblPlant getTblPlant() {
        return this.tblPlant;
    }
    
    public void setTblPlant(TblPlant tblPlant) {
        this.tblPlant = tblPlant;
    }
    public Set getTblVehicleFlights() {
        return this.tblVehicleFlights;
    }
    
    public void setTblVehicleFlights(Set tblVehicleFlights) {
        this.tblVehicleFlights = tblVehicleFlights;
    }
    public Set getTblMappings() {
        return this.tblMappings;
    }
    
    public void setTblMappings(Set tblMappings) {
        this.tblMappings = tblMappings;
    }




}


