package hibernate.pojo;
// Generated 5 Apr, 2015 5:42:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TblExceptions generated by hbm2java
 */
public class TblExceptions  implements java.io.Serializable {


     private BigDecimal IExceptionId;
     private TblEpos tblEpos;
     private TblMapping tblMapping;
     private TblPlant tblPlant;
     private Date dtCreated;
     private Date dtExpectedTime;
     private boolean BIsChecked;

    public TblExceptions() {
    }

	
    public TblExceptions(BigDecimal IExceptionId, TblEpos tblEpos, TblMapping tblMapping, TblPlant tblPlant, boolean BIsChecked) {
        this.IExceptionId = IExceptionId;
        this.tblEpos = tblEpos;
        this.tblMapping = tblMapping;
        this.tblPlant = tblPlant;
        this.BIsChecked = BIsChecked;
    }
    public TblExceptions(BigDecimal IExceptionId, TblEpos tblEpos, TblMapping tblMapping, TblPlant tblPlant, Date dtCreated, Date dtExpectedTime, boolean BIsChecked) {
       this.IExceptionId = IExceptionId;
       this.tblEpos = tblEpos;
       this.tblMapping = tblMapping;
       this.tblPlant = tblPlant;
       this.dtCreated = dtCreated;
       this.dtExpectedTime = dtExpectedTime;
       this.BIsChecked = BIsChecked;
    }
   
    public BigDecimal getIExceptionId() {
        return this.IExceptionId;
    }
    
    public void setIExceptionId(BigDecimal IExceptionId) {
        this.IExceptionId = IExceptionId;
    }
    public TblEpos getTblEpos() {
        return this.tblEpos;
    }
    
    public void setTblEpos(TblEpos tblEpos) {
        this.tblEpos = tblEpos;
    }
    public TblMapping getTblMapping() {
        return this.tblMapping;
    }
    
    public void setTblMapping(TblMapping tblMapping) {
        this.tblMapping = tblMapping;
    }
    public TblPlant getTblPlant() {
        return this.tblPlant;
    }
    
    public void setTblPlant(TblPlant tblPlant) {
        this.tblPlant = tblPlant;
    }
    public Date getDtCreated() {
        return this.dtCreated;
    }
    
    public void setDtCreated(Date dtCreated) {
        this.dtCreated = dtCreated;
    }
    public Date getDtExpectedTime() {
        return this.dtExpectedTime;
    }
    
    public void setDtExpectedTime(Date dtExpectedTime) {
        this.dtExpectedTime = dtExpectedTime;
    }
    public boolean isBIsChecked() {
        return this.BIsChecked;
    }
    
    public void setBIsChecked(boolean BIsChecked) {
        this.BIsChecked = BIsChecked;
    }




}


