package hibernate.pojo;
// Generated Apr 18, 2015 10:03:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;

/**
 * TblLinks generated by hbm2java
 */
public class TblLinks  implements java.io.Serializable {

@Column(columnDefinition = "serial")
     private BigDecimal ILid;
     private TblEpos tblEposByITo;
     private TblEpos tblEposByIFrom;
     private TblPlant tblPlant;
     private BigDecimal NTimediffInMin;

    public TblLinks() {
    }

	
    public TblLinks(BigDecimal ILid, TblPlant tblPlant) {
        this.ILid = ILid;
        this.tblPlant = tblPlant;
    }
    public TblLinks(BigDecimal ILid, TblEpos tblEposByITo, TblEpos tblEposByIFrom, TblPlant tblPlant, BigDecimal NTimediffInMin) {
       this.ILid = ILid;
       this.tblEposByITo = tblEposByITo;
       this.tblEposByIFrom = tblEposByIFrom;
       this.tblPlant = tblPlant;
       this.NTimediffInMin = NTimediffInMin;
    }
   
    public BigDecimal getILid() {
        return this.ILid;
    }
    
    public void setILid(BigDecimal ILid) {
        this.ILid = ILid;
    }
    public TblEpos getTblEposByITo() {
        return this.tblEposByITo;
    }
    
    public void setTblEposByITo(TblEpos tblEposByITo) {
        this.tblEposByITo = tblEposByITo;
    }
    public TblEpos getTblEposByIFrom() {
        return this.tblEposByIFrom;
    }
    
    public void setTblEposByIFrom(TblEpos tblEposByIFrom) {
        this.tblEposByIFrom = tblEposByIFrom;
    }
    public TblPlant getTblPlant() {
        return this.tblPlant;
    }
    
    public void setTblPlant(TblPlant tblPlant) {
        this.tblPlant = tblPlant;
    }
    public BigDecimal getNTimediffInMin() {
        return this.NTimediffInMin;
    }
    
    public void setNTimediffInMin(BigDecimal NTimediffInMin) {
        this.NTimediffInMin = NTimediffInMin;
    }




}


