package hibernate.pojo;
// Generated 5 Apr, 2015 5:42:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblMapping generated by hbm2java
 */
public class TblMapping  implements java.io.Serializable {


     private BigDecimal ITripId;
     private TblDo tblDo;
     private TblDriver tblDriver;
     private TblPlant tblPlant;
     private TblProcess tblProcess;
     private TblTransporter tblTransporter;
     private TblVehicle tblVehicle;
     private BigDecimal ICardId;
     private Date dtCreated;
     private boolean BIsActive;
     private Set<TblVehicleFlight> tblVehicleFlights = new HashSet<TblVehicleFlight>(0);
     private Set<TblExceptions> tblExceptionses = new HashSet<TblExceptions>(0);

    public TblMapping() {
    }

	
    public TblMapping(BigDecimal ITripId, TblPlant tblPlant, TblVehicle tblVehicle, boolean BIsActive) {
        this.ITripId = ITripId;
        this.tblPlant = tblPlant;
        this.tblVehicle = tblVehicle;
        this.BIsActive = BIsActive;
    }
    public TblMapping(BigDecimal ITripId, TblDo tblDo, TblDriver tblDriver, TblPlant tblPlant, TblProcess tblProcess, TblTransporter tblTransporter, TblVehicle tblVehicle, BigDecimal ICardId, Date dtCreated, boolean BIsActive, Set<TblVehicleFlight> tblVehicleFlights, Set<TblExceptions> tblExceptionses) {
       this.ITripId = ITripId;
       this.tblDo = tblDo;
       this.tblDriver = tblDriver;
       this.tblPlant = tblPlant;
       this.tblProcess = tblProcess;
       this.tblTransporter = tblTransporter;
       this.tblVehicle = tblVehicle;
       this.ICardId = ICardId;
       this.dtCreated = dtCreated;
       this.BIsActive = BIsActive;
       this.tblVehicleFlights = tblVehicleFlights;
       this.tblExceptionses = tblExceptionses;
    }
   
    public BigDecimal getITripId() {
        return this.ITripId;
    }
    
    public void setITripId(BigDecimal ITripId) {
        this.ITripId = ITripId;
    }
    public TblDo getTblDo() {
        return this.tblDo;
    }
    
    public void setTblDo(TblDo tblDo) {
        this.tblDo = tblDo;
    }
    public TblDriver getTblDriver() {
        return this.tblDriver;
    }
    
    public void setTblDriver(TblDriver tblDriver) {
        this.tblDriver = tblDriver;
    }
    public TblPlant getTblPlant() {
        return this.tblPlant;
    }
    
    public void setTblPlant(TblPlant tblPlant) {
        this.tblPlant = tblPlant;
    }
    public TblProcess getTblProcess() {
        return this.tblProcess;
    }
    
    public void setTblProcess(TblProcess tblProcess) {
        this.tblProcess = tblProcess;
    }
    public TblTransporter getTblTransporter() {
        return this.tblTransporter;
    }
    
    public void setTblTransporter(TblTransporter tblTransporter) {
        this.tblTransporter = tblTransporter;
    }
    public TblVehicle getTblVehicle() {
        return this.tblVehicle;
    }
    
    public void setTblVehicle(TblVehicle tblVehicle) {
        this.tblVehicle = tblVehicle;
    }
    public BigDecimal getICardId() {
        return this.ICardId;
    }
    
    public void setICardId(BigDecimal ICardId) {
        this.ICardId = ICardId;
    }
    public Date getDtCreated() {
        return this.dtCreated;
    }
    
    public void setDtCreated(Date dtCreated) {
        this.dtCreated = dtCreated;
    }
    public boolean isBIsActive() {
        return this.BIsActive;
    }
    
    public void setBIsActive(boolean BIsActive) {
        this.BIsActive = BIsActive;
    }
    public Set<TblVehicleFlight> getTblVehicleFlights() {
        return this.tblVehicleFlights;
    }
    
    public void setTblVehicleFlights(Set<TblVehicleFlight> tblVehicleFlights) {
        this.tblVehicleFlights = tblVehicleFlights;
    }
    public Set<TblExceptions> getTblExceptionses() {
        return this.tblExceptionses;
    }
    
    public void setTblExceptionses(Set<TblExceptions> tblExceptionses) {
        this.tblExceptionses = tblExceptionses;
    }




}


