package hibernate.pojo;
// Generated Apr 17, 2015 9:43:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;

/**
 * TblPlant generated by hbm2java
 */
public class TblPlant  implements java.io.Serializable {

@Column(columnDefinition = "serial")
     private BigDecimal IPlantId;
     private String TPlantName;
     private String TPlantOwner;
     private Set tblLivePaths = new HashSet(0);
     private Set tblEposes = new HashSet(0);
     private Set tblPathses = new HashSet(0);
     private Set tblExceptionses = new HashSet(0);
     private Set tblUserses = new HashSet(0);
     private Set tblLinkses = new HashSet(0);
     private Set tblDrivers = new HashSet(0);
     private Set tblDos = new HashSet(0);
     private Set tblVehicles = new HashSet(0);
     private Set tblMappings = new HashSet(0);
     private Set tblCards = new HashSet(0);
     private Set tblTransporters = new HashSet(0);
     private Set tblProcesses = new HashSet(0);

    public TblPlant() {
    }

	
    public TblPlant(BigDecimal IPlantId) {
        this.IPlantId = IPlantId;
    }
    public TblPlant(BigDecimal IPlantId, String TPlantName, String TPlantOwner, Set tblLivePaths, Set tblEposes, Set tblPathses, Set tblExceptionses, Set tblUserses, Set tblLinkses, Set tblDrivers, Set tblDos, Set tblVehicles, Set tblMappings, Set tblCards, Set tblTransporters, Set tblProcesses) {
       this.IPlantId = IPlantId;
       this.TPlantName = TPlantName;
       this.TPlantOwner = TPlantOwner;
       this.tblLivePaths = tblLivePaths;
       this.tblEposes = tblEposes;
       this.tblPathses = tblPathses;
       this.tblExceptionses = tblExceptionses;
       this.tblUserses = tblUserses;
       this.tblLinkses = tblLinkses;
       this.tblDrivers = tblDrivers;
       this.tblDos = tblDos;
       this.tblVehicles = tblVehicles;
       this.tblMappings = tblMappings;
       this.tblCards = tblCards;
       this.tblTransporters = tblTransporters;
       this.tblProcesses = tblProcesses;
    }
   
    public BigDecimal getIPlantId() {
        return this.IPlantId;
    }
    
    public void setIPlantId(BigDecimal IPlantId) {
        this.IPlantId = IPlantId;
    }
    public String getTPlantName() {
        return this.TPlantName;
    }
    
    public void setTPlantName(String TPlantName) {
        this.TPlantName = TPlantName;
    }
    public String getTPlantOwner() {
        return this.TPlantOwner;
    }
    
    public void setTPlantOwner(String TPlantOwner) {
        this.TPlantOwner = TPlantOwner;
    }
    public Set getTblLivePaths() {
        return this.tblLivePaths;
    }
    
    public void setTblLivePaths(Set tblLivePaths) {
        this.tblLivePaths = tblLivePaths;
    }
    public Set getTblEposes() {
        return this.tblEposes;
    }
    
    public void setTblEposes(Set tblEposes) {
        this.tblEposes = tblEposes;
    }
    public Set getTblPathses() {
        return this.tblPathses;
    }
    
    public void setTblPathses(Set tblPathses) {
        this.tblPathses = tblPathses;
    }
    public Set getTblExceptionses() {
        return this.tblExceptionses;
    }
    
    public void setTblExceptionses(Set tblExceptionses) {
        this.tblExceptionses = tblExceptionses;
    }
    public Set getTblUserses() {
        return this.tblUserses;
    }
    
    public void setTblUserses(Set tblUserses) {
        this.tblUserses = tblUserses;
    }
    public Set getTblLinkses() {
        return this.tblLinkses;
    }
    
    public void setTblLinkses(Set tblLinkses) {
        this.tblLinkses = tblLinkses;
    }
    public Set getTblDrivers() {
        return this.tblDrivers;
    }
    
    public void setTblDrivers(Set tblDrivers) {
        this.tblDrivers = tblDrivers;
    }
    public Set getTblDos() {
        return this.tblDos;
    }
    
    public void setTblDos(Set tblDos) {
        this.tblDos = tblDos;
    }
    public Set getTblVehicles() {
        return this.tblVehicles;
    }
    
    public void setTblVehicles(Set tblVehicles) {
        this.tblVehicles = tblVehicles;
    }
    public Set getTblMappings() {
        return this.tblMappings;
    }
    
    public void setTblMappings(Set tblMappings) {
        this.tblMappings = tblMappings;
    }
    public Set getTblCards() {
        return this.tblCards;
    }
    
    public void setTblCards(Set tblCards) {
        this.tblCards = tblCards;
    }
    public Set getTblTransporters() {
        return this.tblTransporters;
    }
    
    public void setTblTransporters(Set tblTransporters) {
        this.tblTransporters = tblTransporters;
    }
    public Set getTblProcesses() {
        return this.tblProcesses;
    }
    
    public void setTblProcesses(Set tblProcesses) {
        this.tblProcesses = tblProcesses;
    }




}


