package hibernate.pojo;
// Generated Apr 17, 2015 9:43:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblVehicle generated by hbm2java
 */
public class TblVehicle  implements java.io.Serializable {


     private String TVehicleId;
     private TblPlant tblPlant;
     private String TChasisNo;
     private String TVehicleType;
     private Long ILoadCapacity;
     private String TOwner;
     private String TNationalPermit;
     private Date dtLicenseExpiryDate;
     private Set tblMappings = new HashSet(0);

    public TblVehicle() {
    }

	
    public TblVehicle(String TVehicleId, TblPlant tblPlant) {
        this.TVehicleId = TVehicleId;
        this.tblPlant = tblPlant;
    }
    public TblVehicle(String TVehicleId, TblPlant tblPlant, String TChasisNo, String TVehicleType, Long ILoadCapacity, String TOwner, String TNationalPermit, Date dtLicenseExpiryDate, Set tblMappings) {
       this.TVehicleId = TVehicleId;
       this.tblPlant = tblPlant;
       this.TChasisNo = TChasisNo;
       this.TVehicleType = TVehicleType;
       this.ILoadCapacity = ILoadCapacity;
       this.TOwner = TOwner;
       this.TNationalPermit = TNationalPermit;
       this.dtLicenseExpiryDate = dtLicenseExpiryDate;
       this.tblMappings = tblMappings;
    }
   
    public String getTVehicleId() {
        return this.TVehicleId;
    }
    
    public void setTVehicleId(String TVehicleId) {
        this.TVehicleId = TVehicleId;
    }
    public TblPlant getTblPlant() {
        return this.tblPlant;
    }
    
    public void setTblPlant(TblPlant tblPlant) {
        this.tblPlant = tblPlant;
    }
    public String getTChasisNo() {
        return this.TChasisNo;
    }
    
    public void setTChasisNo(String TChasisNo) {
        this.TChasisNo = TChasisNo;
    }
    public String getTVehicleType() {
        return this.TVehicleType;
    }
    
    public void setTVehicleType(String TVehicleType) {
        this.TVehicleType = TVehicleType;
    }
    public Long getILoadCapacity() {
        return this.ILoadCapacity;
    }
    
    public void setILoadCapacity(Long ILoadCapacity) {
        this.ILoadCapacity = ILoadCapacity;
    }
    public String getTOwner() {
        return this.TOwner;
    }
    
    public void setTOwner(String TOwner) {
        this.TOwner = TOwner;
    }
    public String getTNationalPermit() {
        return this.TNationalPermit;
    }
    
    public void setTNationalPermit(String TNationalPermit) {
        this.TNationalPermit = TNationalPermit;
    }
    public Date getDtLicenseExpiryDate() {
        return this.dtLicenseExpiryDate;
    }
    
    public void setDtLicenseExpiryDate(Date dtLicenseExpiryDate) {
        this.dtLicenseExpiryDate = dtLicenseExpiryDate;
    }
    public Set getTblMappings() {
        return this.tblMappings;
    }
    
    public void setTblMappings(Set tblMappings) {
        this.tblMappings = tblMappings;
    }




}


