package hibernate.pojo;
// Generated 14 Apr, 2015 8:17:11 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TblVehicleFlight generated by hbm2java
 */
public class TblVehicleFlight  implements java.io.Serializable, Comparable<TblVehicleFlight> {


     private BigDecimal IVfid;
     private TblEpos tblEpos;
     private TblMapping tblMapping;
     private BigDecimal IPlantId;
     private Date dtTime;
     private BigDecimal ICardId;

    public TblVehicleFlight() {
    }

	
    public TblVehicleFlight(BigDecimal IVfid, TblEpos tblEpos, TblMapping tblMapping, BigDecimal IPlantId, BigDecimal ICardId) {
        this.IVfid = IVfid;
        this.tblEpos = tblEpos;
        this.tblMapping = tblMapping;
        this.IPlantId = IPlantId;
        this.ICardId = ICardId;
    }
    public TblVehicleFlight(BigDecimal IVfid, TblEpos tblEpos, TblMapping tblMapping, BigDecimal IPlantId, Date dtTime, BigDecimal ICardId) {
       this.IVfid = IVfid;
       this.tblEpos = tblEpos;
       this.tblMapping = tblMapping;
       this.IPlantId = IPlantId;
       this.dtTime = dtTime;
       this.ICardId = ICardId;
    }
   
    public BigDecimal getIVfid() {
        return this.IVfid;
    }
    
    public void setIVfid(BigDecimal IVfid) {
        this.IVfid = IVfid;
    }
    public TblEpos getTblEpos() {
        return this.tblEpos;
    }
    
    public void setTblEpos(TblEpos tblEpos) {
        this.tblEpos = tblEpos;
    }
    public TblMapping getTblMapping() {
        return this.tblMapping;
    }
    
    public void setTblMapping(TblMapping tblMapping) {
        this.tblMapping = tblMapping;
    }
    public BigDecimal getIPlantId() {
        return this.IPlantId;
    }
    
    public void setIPlantId(BigDecimal IPlantId) {
        this.IPlantId = IPlantId;
    }
    public Date getDtTime() {
        return this.dtTime;
    }
    
    public void setDtTime(Date dtTime) {
        this.dtTime = dtTime;
    }
    public BigDecimal getICardId() {
        return this.ICardId;
    }
    
    public void setICardId(BigDecimal ICardId) {
        this.ICardId = ICardId;
    }

    public int compareTo(TblVehicleFlight e)
    {
        return this.IVfid.compareTo(e.IVfid);
    }

}


